### PR TITLE
Issue #21, #22, #23, #24 fixes

### PR DESCRIPTION
**Pull request by giuliopulina**
Upgraded libraries to support external references import without providing ./ prefix in paths, resolved some issues related to produces/consumes validation, upgraded some maven libraries and bytebuddy (along with a small code change) to make the project usable within java 11.

@khoma @oyeli

### CODE REVIEW

**Comment by warden** [comment]
Those fixes are quite needed, @sylvainlaurent would you have some time to review and release new version?

**Comment by giuliopulina** [comment]
@sylvainlaurent will you be able to review this PR? 
By the way, if you're not interested anymore in this project (or, simply, you don't have enough time), I can propose myself as a collaborator

**Comment by giuliopulina** [comment]
As more than six months have passed, I'm closing this PR and in the next days I will release the changes on Maven Central from my fork https://github.com/giuliopulina/swagger-validator-maven-plugin

**Comment by giuliopulina** [comment]
For whom is interested, I published changes contained in this PR into this project:

```xml
<groupId>com.github.giuliopulina</groupId>
<artifactId>swagger-validator-maven-plugin</artifactId>
<version>1.0.0</version>
```

**Comment by warden** [comment]
Thanks @giuliopulina for this work and comment, that's really valuable and I'm interested in using your changes. One remark: I think it would be better to stick to semantic versioning, so assuming that you based your changes on the newest version of this plugin, you should publish version `1.2.6` as your artifact, so that it is clear which "feature-set" it is basing on.

**Comment by giuliopulina** [comment]
I think you are right, probably but I'm not sure if putting "giuliopulina" in the version number will help much or is the right thing to do. 
From what I read (I never did something similar in the past) resetting the version number when forking is the most common approach.
Maybe using a meaningful classifier could help? Any suggestion?

**Comment by warden** [comment]
For me it is unclear to reset version number on forking, because it will make it harder for anyone (including you) to track later which feature-set are you on in your fork. I generally try to follow https://semver.org/ description and in this case I'd try to use https://semver.org/#spec-item-10 (assuming of course the changes from your fork will finally land in the upstream one day :-) ) - hope that helps!

**Pull request closed without merging**
